spring:
  application:
    name: skmns-codingtest

  h2:
    console:
      enabled: true
      path: /skmns

  datasource:
    url: jdbc:h2:mem:skmns
    driver-class-name: org.h2.Driver
    username: skmns

  jpa:
    open-in-view: false              
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        hbm2ddl:
          '[import_files]': import.sql  
        '[format_sql]': true            
        '[show_sql]': true             

logging:
  level:
    '[com.skmns.codingtest]': DEBUG
