INSERT INTO auth (username, password) VALUES ('skmns01', '0000');
INSERT INTO auth (username, password) VALUES ('skmns02', '1111');

INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('First', '1111', 1, 1001, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Second', '2222', 1, 1010, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Third', '3333', 1, 1011, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Fourth', '4444', 1, 1020, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Fifth', '5555', 2, 1035, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Sixth', '6666', 2, 1050, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Seventh', '7777', 2, 1061, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Eighth', '8888', 1, 1077, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Ninth', '9999', 2, 1088, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Tenth', '1010', 1, 1090, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Eleventh', '1111', 1, 1100, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Twelfth', '1212', 2, 1110, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Thirteenth', '1313', 1, 1120, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Fourteenth', '1414', 2, 1130, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Fifteenth', '1515', 1, 1140, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Sixteenth', '1616', 1, 1150, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Seventeenth', '1717', 2, 1160, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Eighteenth', '1818', 2, 1170, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Nineteenth', '1919', 1, 1180, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Twentieth', '2020', 1, 1190, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Twenty-first', '2121', 2, 1200, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Twenty-second', '2222', 2, 1210, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Twenty-third', '2323', 1, 1220, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Twenty-fourth', '2424', 1, 1230, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Twenty-fifth', '2525', 2, 1240, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Twenty-sixth', '2626', 2, 1250, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Twenty-seventh', '2727', 1, 1260, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Twenty-eighth', '2828', 1, 1270, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Twenty-ninth', '2929', 2, 1280, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Thirtieth', '3030', 2, 1290, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Thirty-first', '3131', 1, 1300, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Thirty-second', '3232', 2, 1310, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Thirty-third', '3333', 1, 1320, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Thirty-fourth', '3434', 2, 1330, NOW(), false);
INSERT INTO articles (title, content, user_id, view_count, created_at, has_file) VALUES ('Thirty-fifth', '3535', 1, 1340, NOW(), false);

